### ISSUE TITLE
0.1.5 breaks initial-state-compat behavior

### ISSUE THREAD

**Issue by chrisirhc** [fusionjs/fusion-plugin-http-handler#73]
### Type of issue

Bug

### Description

This seems to have broken the `@uber/fusion-plugin-initial-state-compat` behavior, since it no longer finds the `res.locals.state` as the `initial-state-compat` always runs before the express handlers that add `res.locals`.

### Current behavior

initial-state-compat no longer adds any state from initial state loaded from express hooks/plugins that call `res.putState`.

### Expected behavior

initial-state-compat adds initial state as expected.

### Steps to reproduce

1. Upgrade from fusion-plugin-http-handler 0.1.4 to 0.1.5

### Your environment

* fusion-plugin-http-handler version: 0.1.5
* @uber/fusion-plugin-initial-state-compat: 0.1.2

* Node.js version (`node --version`): v8.12.0

_Originally posted by @chrisirhc in https://github.com/fusionjs/fusion-plugin-http-handler/pull/67#issuecomment-466693617_

**Comment by ganemone** [comment]
This is tough because the old version also had a bug which can only be fixed by changing this behavior. I don't think we will revert this, but I would recommend finishing migrating the calls to `putState` into using the `GetInitialStateToken` from `fusion-plugin-react-redux`

**Comment by chrisirhc** [comment]
@ganemone shouldn't we notify all users of get-initial-state-compat to not upgrade to 0.1.5 of http-handler?
This was a timesink for me as I was debugging why the upgrade wasn't smooth.
